export const GET_ALL_PROJECT_CATEGORY = 'GET_ALL_PROJECT_CATEGORY';
export const GET_ALL_PROJECT_CATEGORY_SAGA = 'GET_ALL_PROJECT_CATEGORY_SAGA';
export const CREATE_PROJECT_SAGA = 'CREATE_PROJECT_SAGA';
export const GET_PROJECT_SAGA = 'GET_PROJECT_SAGA';
export const UPDATE_PROJECT_SAGA = 'UPDATE_PROJECT_SAGA';
export const DELETE_PROJECT_SAGA = 'DELETE_PROJECT_SAGA';

export const GET_ALL_PROJECTS = 'GET_ALL_PROJECTS';
export const GET_ALL_PROJECTS_SAGA = 'GET_ALL_PROJECTS_SAGA';

export const GET_PROJECT_DETAILS_SAGA = 'GET_PROJECT_DETAILS_SAGA';
export const ADD_USER_PROJECT_SAGA = 'ADD_USER_PROJECT_SAGA';
export const REMOVE_USER_PROJECT_SAGA = 'REMOVE_USER_PROJECT_SAGA';
export const EDIT_PROJECT = 'EDIT_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const PUT_PROJECT_DETAILS = 'PUT_PROJECT_DETAILS';
// DRAWER
export const OPEN_DRAWER = 'OPEN_DRAWER';
export const CLOSE_DRAWER = 'CLOSE_DRAWER';
export const OPEN_FORM_EDIT_PROJECT = 'OPEN_FORM_EDIT_PROJECT';
export const SET_SUBMIT_EDIT_PROJECT = 'SET_SUBMIT_EDIT_PROJECT';
export const OPEN_FORM_CREATE_TASK = 'OPEN_FORM_CREATE_TASK';
export const SET_SUBMIT_CREATE_TASK = 'SET_SUBMIT_CREATE_TASK';

// USER
export const USER_SIGNIN_API = 'USER_SIGNIN_API';
export const USLOGIN = 'USLOGIN';
export const GET_USER_API = 'GET_USER_API';
export const GET_USER_SEARCH = 'GET_USER_SEARCH';
export const GET_USER_BY_PROJECT_ID = 'GET_USER_BY_PROJECT_ID';
export const GET_USER_BY_PROJECT_ID_SAGA = 'GET_USER_BY_PROJECT_ID_SAGA';
